# just a quick compose file to make testing with the register easy
version: '3.9'
volumes:
  redis-data:
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: redis-server
  register:
    image: daylinmicroservices/register
    ports:
      - 2999:2999
    environment:
      - redisAddress=host.docker.internal